# Introduction to numpy

In [2]:
import numpy as np
np.__version__

'1.21.2'

Intro to python list

In [3]:
# python list example
gpas_as_list = [3.5, 3.826, 2.5]

In [4]:
# element can be append in a list
gpas_as_list.append(4.0)

In [5]:
# can have multiple data type
gpas_as_list.insert(0,'Physics')

In [6]:
# item can be removed
gpas_as_list.pop(0)

'Physics'

In [7]:
gpas_as_list


[3.5, 3.826, 2.5, 4.0]

In [8]:
# turn the list into array
gpas = np.array(gpas_as_list)
# to see dtails run `?gpas`

In [9]:
# to see data type
gpas.dtype


dtype('float64')

In [10]:
# to see item size
gpas.itemsize

8

In [11]:
# number of element of an array
gpas.size

4

In [12]:
# length of object
len(gpas)

4

In [23]:
gpas.nbytes

32

In [25]:
# let's create an array of students
students_gpas = np.array([
    [3.5, 3.826, 2.5, 4.0],
    [3.5, 2.7, 4.0, 4.0],
    [4.0, 3.88, 3.96, 3.0]
], np.float16)
students_gpas

array([[3.5  , 3.826, 2.5  , 4.   ],
       [3.5  , 2.7  , 4.   , 4.   ],
       [4.   , 3.88 , 3.96 , 3.   ]], dtype=float16)

In [26]:
# to see property 
students_gpas.ndim

2

In [27]:
# to see how many elements in each dimension
students_gpas.shape

(3, 4)

In [28]:
# see total elements
students_gpas.size

12

In [29]:
# see first dimension
len(students_gpas)

3

In [30]:
# how many byte used per item
students_gpas.itemsize

2

In [31]:
# calculate total space take
students_gpas.itemsize * students_gpas.size

24

In [32]:
# check all info about an array
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1800e40bab0
byteorder:  little
byteswap:  False
type: float16


# 100DaysOfCode study plan
## make a np array of zeros , later we'll add how long we've studied each day

## About data type of NumPy array
[NumPy Data Type](https://numpy.org/doc/stable/user/basics.types.html)

In [15]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [16]:
%whos

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list    list       n=4
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os              module     <module 'os' from 'c:\\us<...>n\\python39\\lib\\os.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes
sys             module     <module 'sys' (built-in)>


In [21]:
# set our first day of min, let's say 150 min
study_minutes[0] = 150
first_day_minutes = study_minutes[0]
first_day_minutes

150

In [18]:
# its known as sceller data type
type(first_day_minutes)

numpy.uint16

In [19]:
# set 2nd day
study_minutes[1] = 60
second_day_minutes = study_minutes[1]
second_day_minutes

60

In [22]:
# set day 3 to day 6
# let's just say we'll code day 3,4,5,6 -> 80, 60, 30, 90

study_minutes [2:6] = [80, 60, 30, 90]
study_minutes

array([150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)